// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_easy_money = "CgkIu8LriKAEEAIQJw"; // <GPGSID>
        public const string achievement_straight = "CgkIu8LriKAEEAIQBw"; // <GPGSID>
        public const string achievement_corpseman = "CgkIu8LriKAEEAIQDw"; // <GPGSID>
        public const string achievement_whitesmith = "CgkIu8LriKAEEAIQJQ"; // <GPGSID>
        public const string achievement_fixer = "CgkIu8LriKAEEAIQEw"; // <GPGSID>
        public const string achievement_merchant = "CgkIu8LriKAEEAIQIw"; // <GPGSID>
        public const string achievement_blood_money = "CgkIu8LriKAEEAIQKg"; // <GPGSID>
        public const string achievement_the_unstoppable_force = "CgkIu8LriKAEEAIQDg"; // <GPGSID>
        public const string achievement_war_bounds = "CgkIu8LriKAEEAIQKA"; // <GPGSID>
        public const string achievement_rite_of_first = "CgkIu8LriKAEEAIQCw"; // <GPGSID>
        public const string achievement_honey = "CgkIu8LriKAEEAIQCA"; // <GPGSID>
        public const string achievement_hour = "CgkIu8LriKAEEAIQLQ"; // <GPGSID>
        public const string leaderboard_top_pleya_in_da_world = "CgkIu8LriKAEEAIQAg"; // <GPGSID>
        public const string achievement_the_cleaner = "CgkIu8LriKAEEAIQDA"; // <GPGSID>
        public const string achievement_mega_carry = "CgkIu8LriKAEEAIQFg"; // <GPGSID>
        public const string achievement_imba = "CgkIu8LriKAEEAIQGQ"; // <GPGSID>
        public const string achievement_ho_ho_ha_ha = "CgkIu8LriKAEEAIQGg"; // <GPGSID>
        public const string achievement_century = "CgkIu8LriKAEEAIQMA"; // <GPGSID>
        public const string achievement_killanthropist = "CgkIu8LriKAEEAIQJg"; // <GPGSID>
        public const string achievement_mega_support = "CgkIu8LriKAEEAIQGA"; // <GPGSID>
        public const string achievement_clean_sweep = "CgkIu8LriKAEEAIQEQ"; // <GPGSID>
        public const string achievement_just_a_taste = "CgkIu8LriKAEEAIQHg"; // <GPGSID>
        public const string achievement_flush = "CgkIu8LriKAEEAIQCQ"; // <GPGSID>
        public const string achievement_its_not_time_yet = "CgkIu8LriKAEEAIQFA"; // <GPGSID>
        public const string achievement_let_me_go_my_dear = "CgkIu8LriKAEEAIQFQ"; // <GPGSID>
        public const string achievement_grac = "CgkIu8LriKAEEAIQHQ"; // <GPGSID>
        public const string achievement_godlike = "CgkIu8LriKAEEAIQBg"; // <GPGSID>
        public const string achievement_full_house = "CgkIu8LriKAEEAIQCg"; // <GPGSID>
        public const string leaderboard_playerexperience = "CgkIu8LriKAEEAIQMQ"; // <GPGSID>
        public const string achievement_leeter_of_men = "CgkIu8LriKAEEAIQKw"; // <GPGSID>
        public const string achievement_promoted = "CgkIu8LriKAEEAIQIA"; // <GPGSID>
        public const string achievement_month = "CgkIu8LriKAEEAIQLg"; // <GPGSID>
        public const string achievement_year = "CgkIu8LriKAEEAIQLw"; // <GPGSID>
        public const string achievement_first_ones_free = "CgkIu8LriKAEEAIQBQ"; // <GPGSID>
        public const string achievement_blacksmith = "CgkIu8LriKAEEAIQJA"; // <GPGSID>
        public const string achievement_commerce = "CgkIu8LriKAEEAIQEg"; // <GPGSID>
        public const string achievement_wild_chase = "CgkIu8LriKAEEAIQDQ"; // <GPGSID>
        public const string achievement_mega_mage = "CgkIu8LriKAEEAIQFw"; // <GPGSID>
        public const string achievement_finish_him = "CgkIu8LriKAEEAIQLA"; // <GPGSID>
        public const string achievement_awardist = "CgkIu8LriKAEEAIQIg"; // <GPGSID>
        public const string achievement_newb_world_order = "CgkIu8LriKAEEAIQHw"; // <GPGSID>
        public const string achievement_the_magic_ends_here = "CgkIu8LriKAEEAIQHA"; // <GPGSID>
        public const string achievement_pianist = "CgkIu8LriKAEEAIQGw"; // <GPGSID>
        public const string achievement_i_can_quit_any_time = "CgkIu8LriKAEEAIQIQ"; // <GPGSID>
        public const string achievement_spoils_of_war = "CgkIu8LriKAEEAIQKQ"; // <GPGSID>
        public const string achievement_god_of_war = "CgkIu8LriKAEEAIQEA"; // <GPGSID>

}

